[package]
name = "command-execution-service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
env_logger = "0.10"
base64 = "0.21"
regex = "1.7"
urlencoding = "2.1"
